### ISSUE TITLE
`Option` is only a type, it cannot be imported as a value.

### ISSUE THREAD

**Issue by darikoko** [pta2002/gleam-filespy#7]
in filespy.gleam the first lines are:
```gleam
import gleam/option.{None, Option,Some}
import gleam/otp/actor.{ErlangStartResult}
import gleam/erlang/atom.{Atom}
```
which gives us a warning about Option, ErlangStartResult and Atom (... is only a type, it cannot be imported as a value.), if I fix this manually with the following lines it seems to works  : 

```
import gleam/option.{None, type Option,Some}
import gleam/otp/actor.{type ErlangStartResult}
import gleam/erlang/atom.{type Atom}
```

can you update the source code to fix this ? Thanks a lot

**Comment by pta2002** [comment]
Sorry for not having updated this yet, I think #8 solves this

**Comment by pta2002** [comment]
Actually, the change had already been made, and I just hadn't published it yet. Will do now.

**Comment by pta2002** [comment]
Actually, sorry for still bringing this up once again, but it should have been published already by the time you commented this. Either way, ensure you're using v0.5.0, it's definitely fixed there.
